name: Deploy to GitHub Pages

on:
  # 每次 push 到 main 分支时自动触发
  push:
    branches: [ main ]
  # 允许您在 Github Actions 页面上手动触发部署
  workflow_dispatch:

# 权限设置，允许 Action 推送静态内容到 Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          node-version: 20
          package-manager: npm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
